version: 2

models:
  - name: stg_matches
    columns:
      - name: match_id
        tests:
          - not_null
          - unique
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
      - name: home_team_id
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
      - name: away_team_id
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1

  - name: stg_player_match_stats
    columns:
      - name: match_id
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
      - name: team_id
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
      - name: player_id
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1

  - name: stg_match_events
    columns:
      - name: match_id
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
      - name: team_id
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
      - name: primary_player_id
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
      - name: secondary_player_id
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1